/*
Copyright 2023 Red Hat, Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/s1061123/bridge-operator/pkg/apis/openshift.io/v1alpha1"
	openshiftiov1alpha1 "github.com/s1061123/bridge-operator/pkg/client/applyconfiguration/openshift.io/v1alpha1"
	scheme "github.com/s1061123/bridge-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BridgeInformationsGetter has a method to return a BridgeInformationInterface.
// A group's client should implement this interface.
type BridgeInformationsGetter interface {
	BridgeInformations() BridgeInformationInterface
}

// BridgeInformationInterface has methods to work with BridgeInformation resources.
type BridgeInformationInterface interface {
	Create(ctx context.Context, bridgeInformation *v1alpha1.BridgeInformation, opts v1.CreateOptions) (*v1alpha1.BridgeInformation, error)
	Update(ctx context.Context, bridgeInformation *v1alpha1.BridgeInformation, opts v1.UpdateOptions) (*v1alpha1.BridgeInformation, error)
	UpdateStatus(ctx context.Context, bridgeInformation *v1alpha1.BridgeInformation, opts v1.UpdateOptions) (*v1alpha1.BridgeInformation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.BridgeInformation, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.BridgeInformationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BridgeInformation, err error)
	Apply(ctx context.Context, bridgeInformation *openshiftiov1alpha1.BridgeInformationApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.BridgeInformation, err error)
	ApplyStatus(ctx context.Context, bridgeInformation *openshiftiov1alpha1.BridgeInformationApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.BridgeInformation, err error)
	BridgeInformationExpansion
}

// bridgeInformations implements BridgeInformationInterface
type bridgeInformations struct {
	client rest.Interface
}

// newBridgeInformations returns a BridgeInformations
func newBridgeInformations(c *OpenShiftIOV1alpha1Client) *bridgeInformations {
	return &bridgeInformations{
		client: c.RESTClient(),
	}
}

// Get takes name of the bridgeInformation, and returns the corresponding bridgeInformation object, and an error if there is any.
func (c *bridgeInformations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BridgeInformation, err error) {
	result = &v1alpha1.BridgeInformation{}
	err = c.client.Get().
		Resource("bridge-informations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BridgeInformations that match those selectors.
func (c *bridgeInformations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BridgeInformationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.BridgeInformationList{}
	err = c.client.Get().
		Resource("bridge-informations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested bridgeInformations.
func (c *bridgeInformations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("bridge-informations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a bridgeInformation and creates it.  Returns the server's representation of the bridgeInformation, and an error, if there is any.
func (c *bridgeInformations) Create(ctx context.Context, bridgeInformation *v1alpha1.BridgeInformation, opts v1.CreateOptions) (result *v1alpha1.BridgeInformation, err error) {
	result = &v1alpha1.BridgeInformation{}
	err = c.client.Post().
		Resource("bridge-informations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bridgeInformation).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a bridgeInformation and updates it. Returns the server's representation of the bridgeInformation, and an error, if there is any.
func (c *bridgeInformations) Update(ctx context.Context, bridgeInformation *v1alpha1.BridgeInformation, opts v1.UpdateOptions) (result *v1alpha1.BridgeInformation, err error) {
	result = &v1alpha1.BridgeInformation{}
	err = c.client.Put().
		Resource("bridge-informations").
		Name(bridgeInformation.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bridgeInformation).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *bridgeInformations) UpdateStatus(ctx context.Context, bridgeInformation *v1alpha1.BridgeInformation, opts v1.UpdateOptions) (result *v1alpha1.BridgeInformation, err error) {
	result = &v1alpha1.BridgeInformation{}
	err = c.client.Put().
		Resource("bridge-informations").
		Name(bridgeInformation.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bridgeInformation).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the bridgeInformation and deletes it. Returns an error if one occurs.
func (c *bridgeInformations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("bridge-informations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *bridgeInformations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("bridge-informations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched bridgeInformation.
func (c *bridgeInformations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BridgeInformation, err error) {
	result = &v1alpha1.BridgeInformation{}
	err = c.client.Patch(pt).
		Resource("bridge-informations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied bridgeInformation.
func (c *bridgeInformations) Apply(ctx context.Context, bridgeInformation *openshiftiov1alpha1.BridgeInformationApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.BridgeInformation, err error) {
	if bridgeInformation == nil {
		return nil, fmt.Errorf("bridgeInformation provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(bridgeInformation)
	if err != nil {
		return nil, err
	}
	name := bridgeInformation.Name
	if name == nil {
		return nil, fmt.Errorf("bridgeInformation.Name must be provided to Apply")
	}
	result = &v1alpha1.BridgeInformation{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("bridge-informations").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *bridgeInformations) ApplyStatus(ctx context.Context, bridgeInformation *openshiftiov1alpha1.BridgeInformationApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.BridgeInformation, err error) {
	if bridgeInformation == nil {
		return nil, fmt.Errorf("bridgeInformation provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(bridgeInformation)
	if err != nil {
		return nil, err
	}

	name := bridgeInformation.Name
	if name == nil {
		return nil, fmt.Errorf("bridgeInformation.Name must be provided to Apply")
	}

	result = &v1alpha1.BridgeInformation{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("bridge-informations").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
