/*
Copyright 2023 Red Hat, Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/s1061123/bridge-operator/pkg/apis/openshift.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBridgeNodeStatuses implements BridgeNodeStatusInterface
type FakeBridgeNodeStatuses struct {
	Fake *FakeOpenShiftIOV1alpha1
	ns   string
}

var bridgenodestatusesResource = schema.GroupVersionResource{Group: "openshift.io", Version: "v1alpha1", Resource: "bridge-node-status"}

var bridgenodestatusesKind = schema.GroupVersionKind{Group: "openshift.io", Version: "v1alpha1", Kind: "BridgeNodeStatus"}

// Get takes name of the bridgeNodeStatus, and returns the corresponding bridgeNodeStatus object, and an error if there is any.
func (c *FakeBridgeNodeStatuses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BridgeNodeStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bridgenodestatusesResource, c.ns, name), &v1alpha1.BridgeNodeStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BridgeNodeStatus), err
}

// List takes label and field selectors, and returns the list of BridgeNodeStatuses that match those selectors.
func (c *FakeBridgeNodeStatuses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BridgeNodeStatusList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bridgenodestatusesResource, bridgenodestatusesKind, c.ns, opts), &v1alpha1.BridgeNodeStatusList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BridgeNodeStatusList{ListMeta: obj.(*v1alpha1.BridgeNodeStatusList).ListMeta}
	for _, item := range obj.(*v1alpha1.BridgeNodeStatusList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bridgeNodeStatuses.
func (c *FakeBridgeNodeStatuses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bridgenodestatusesResource, c.ns, opts))

}

// Create takes the representation of a bridgeNodeStatus and creates it.  Returns the server's representation of the bridgeNodeStatus, and an error, if there is any.
func (c *FakeBridgeNodeStatuses) Create(ctx context.Context, bridgeNodeStatus *v1alpha1.BridgeNodeStatus, opts v1.CreateOptions) (result *v1alpha1.BridgeNodeStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bridgenodestatusesResource, c.ns, bridgeNodeStatus), &v1alpha1.BridgeNodeStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BridgeNodeStatus), err
}

// Update takes the representation of a bridgeNodeStatus and updates it. Returns the server's representation of the bridgeNodeStatus, and an error, if there is any.
func (c *FakeBridgeNodeStatuses) Update(ctx context.Context, bridgeNodeStatus *v1alpha1.BridgeNodeStatus, opts v1.UpdateOptions) (result *v1alpha1.BridgeNodeStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bridgenodestatusesResource, c.ns, bridgeNodeStatus), &v1alpha1.BridgeNodeStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BridgeNodeStatus), err
}

// Delete takes name of the bridgeNodeStatus and deletes it. Returns an error if one occurs.
func (c *FakeBridgeNodeStatuses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bridgenodestatusesResource, c.ns, name), &v1alpha1.BridgeNodeStatus{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBridgeNodeStatuses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bridgenodestatusesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BridgeNodeStatusList{})
	return err
}

// Patch applies the patch and returns the patched bridgeNodeStatus.
func (c *FakeBridgeNodeStatuses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BridgeNodeStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bridgenodestatusesResource, c.ns, name, pt, data, subresources...), &v1alpha1.BridgeNodeStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BridgeNodeStatus), err
}
